spring:
  application:
    name: devpro-backend
  profiles:
    default: local
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
